services:
  mysql:
    image: mysql:8.0
    container_name: medic-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: medic_db
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    # NDRYSHIMI KETU: Shto rrugen e sakt te folderit
    build: ./medic-data-core/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=medic_db
      - JWT_SECRET=supersecret
    depends_on:
      - mysql

  hospital-service:
    # NDRYSHIMI KETU: Shto rrugen e sakt te folderit
    build: ./medic-data-core/hospital-service
    container_name: hospital-service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=medic_db
      - JWT_SECRET=supersecret
    depends_on:
      - mysql

volumes:
  mysql_data: